/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import java.awt.Image;
import java.awt.Graphics;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ITSEPT
 */


public class menu_utama extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private final Connection conn = new koneksi().connect();
    private form_jm_personal FJP;
    private form_jm_ukm FJU;
    private form_jm_kpr FJK;
    private form_kr_ukm FKU;
    private form_kr_bg FKB;
    private form_pinjam_personal FPP;
    private form_pinjam_ukm FPU;
    private form_pinjam_kpr FPK;
    private form_pinjam_kr_bg FPG;
    private form_pinjam_kr_ukm FPR;
    private buat_user BU;
    private form_pengembalian FPE;
 
    
        
    private void initForm(){
        FJP = new form_jm_personal();
        FJU = new form_jm_ukm();
        FJK = new form_jm_kpr();
        FKU = new form_kr_ukm();
        FKB = new form_kr_bg();
        FPP = new form_pinjam_personal();
        FPU = new form_pinjam_ukm();
        FPK = new form_pinjam_kpr();
        FPG = new form_pinjam_kr_bg();
        FPR = new form_pinjam_kr_ukm();
        BU = new buat_user();
        FPE = new form_pengembalian();
        
    }

    
    public menu_utama() {
        initComponents();
        initForm();
        jam();
        lbltgl.setText(new SimpleDateFormat("dd / MMMM / YYYY").format(new java.util.Date()));
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/gambar/kredit.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jPanel1 = new javax.swing.JPanel();
        infouser = new javax.swing.JLabel();
        infonama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbljam = new javax.swing.JLabel();
        lbltgl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout_ = new javax.swing.JLabel();
        exit_ = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        buat_user = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        keluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_jm_personal = new javax.swing.JMenuItem();
        menu_jm_ukm = new javax.swing.JMenuItem();
        menu_jm_kpr = new javax.swing.JMenuItem();
        menu_kr_bg = new javax.swing.JMenuItem();
        menu_kr_ukm = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_pinjam_personal = new javax.swing.JMenuItem();
        menu_pinjam_jm_ukm = new javax.swing.JMenuItem();
        menu_pinjam_jm_kpr = new javax.swing.JMenuItem();
        menu_pinjam_kr_bg = new javax.swing.JMenuItem();
        menu_pinjam_kr_ukm = new javax.swing.JMenuItem();
        menu_pengembalian = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jDesktopPane1.setMinimumSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        infouser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        infouser.setForeground(new java.awt.Color(255, 255, 255));
        infouser.setText("-");

        infonama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        infonama.setForeground(new java.awt.Color(255, 255, 255));
        infonama.setText("-");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User ID     :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama        :");

        lbljam.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbljam.setForeground(new java.awt.Color(255, 0, 0));
        lbljam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbljam.setText("jam");

        lbltgl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltgl.setForeground(new java.awt.Color(255, 255, 255));
        lbltgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltgl.setText("Tanggal");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELAMAT DATANG");

        logout_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout_.setForeground(java.awt.Color.red);
        logout_.setText("Logout");
        logout_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout_MousePressed(evt);
            }
        });

        exit_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exit_.setForeground(java.awt.Color.red);
        exit_.setText("Exit");
        exit_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit_MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logout_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit_))
                    .addComponent(lbltgl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbljam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(infouser))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(infonama)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infouser)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infonama)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addComponent(lbljam)
                .addGap(18, 18, 18)
                .addComponent(lbltgl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout_)
                    .addComponent(exit_))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(936, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenu1.setText("System");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buat_user.setText("Buat user");
        buat_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buat_userActionPerformed(evt);
            }
        });
        jMenu1.add(buat_user);

        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });
        jMenu1.add(logout);

        keluar.setText("Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                keluarMousePressed(evt);
            }
        });
        jMenu1.add(keluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Entry Data");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu_jm_personal.setText("Monitoring Jaminan Personal");
        menu_jm_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jm_personalActionPerformed(evt);
            }
        });
        jMenu2.add(menu_jm_personal);

        menu_jm_ukm.setText("Monitoring Jaminan UKM");
        menu_jm_ukm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jm_ukmActionPerformed(evt);
            }
        });
        jMenu2.add(menu_jm_ukm);

        menu_jm_kpr.setText("Monitoring Jaminan KPR");
        menu_jm_kpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_jm_kprActionPerformed(evt);
            }
        });
        jMenu2.add(menu_jm_kpr);

        menu_kr_bg.setText("Kredit Bank Garansi");
        menu_kr_bg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_kr_bgActionPerformed(evt);
            }
        });
        jMenu2.add(menu_kr_bg);

        menu_kr_ukm.setText("Kredit UKM");
        menu_kr_ukm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_kr_ukmActionPerformed(evt);
            }
        });
        jMenu2.add(menu_kr_ukm);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Transaksi");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu_pinjam_personal.setText("Peminjaman Dokumen Jaminan Personal");
        menu_pinjam_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pinjam_personalActionPerformed(evt);
            }
        });
        jMenu4.add(menu_pinjam_personal);

        menu_pinjam_jm_ukm.setText("Peminjaman Dokumen Jaminan UKM");
        menu_pinjam_jm_ukm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pinjam_jm_ukmActionPerformed(evt);
            }
        });
        jMenu4.add(menu_pinjam_jm_ukm);

        menu_pinjam_jm_kpr.setText("Peminjaman Dokumen Jaminan KPR");
        menu_pinjam_jm_kpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pinjam_jm_kprActionPerformed(evt);
            }
        });
        jMenu4.add(menu_pinjam_jm_kpr);

        menu_pinjam_kr_bg.setText("Peminjaman Dokumen Kredit Bank Garansi");
        menu_pinjam_kr_bg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pinjam_kr_bgActionPerformed(evt);
            }
        });
        jMenu4.add(menu_pinjam_kr_bg);

        menu_pinjam_kr_ukm.setText("Peminjaman Dokumen Kredit UKM");
        menu_pinjam_kr_ukm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pinjam_kr_ukmActionPerformed(evt);
            }
        });
        jMenu4.add(menu_pinjam_kr_ukm);

        menu_pengembalian.setText("Pengembalian Dokumen");
        menu_pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pengembalianActionPerformed(evt);
            }
        });
        jMenu4.add(menu_pengembalian);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_jm_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jm_personalActionPerformed
        // TODO add your handling code here:
            if (!FJP.isVisible()) {
        jDesktopPane1.add(FJP);
        FJP.show();
        }
    }//GEN-LAST:event_menu_jm_personalActionPerformed

    private void menu_jm_ukmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jm_ukmActionPerformed
        // TODO add your handling code here:
             if (!FJU.isVisible()) {
        jDesktopPane1.add(FJU);
        FJU.show();
       }
    }//GEN-LAST:event_menu_jm_ukmActionPerformed

    private void menu_jm_kprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_jm_kprActionPerformed
        // TODO add your handling code here:
            if (!FJK.isVisible()) {
        jDesktopPane1.add(FJK);
        FJK.show();
        }
    }//GEN-LAST:event_menu_jm_kprActionPerformed

    private void menu_pinjam_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pinjam_personalActionPerformed
        // TODO add your handling code here:
           if (!FPP.isVisible()) {
        jDesktopPane1.add(FPP);
        FPP.show();
        }
    }//GEN-LAST:event_menu_pinjam_personalActionPerformed

    private void buat_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buat_userActionPerformed
        // TODO add your handling code here:
           if (!BU.isVisible()) {
        jDesktopPane1.add(BU);
        BU.show();
        }
    }//GEN-LAST:event_buat_userActionPerformed

    private void menu_pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pengembalianActionPerformed
        // TODO add your handling code here:
           if (!FPE.isVisible()) {
        jDesktopPane1.add(FPE);
        FPE.show();
        }
    }//GEN-LAST:event_menu_pengembalianActionPerformed

    private void menu_pinjam_jm_ukmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pinjam_jm_ukmActionPerformed
        // TODO add your handling code here:
           if (!FPU.isVisible()) {
        jDesktopPane1.add(FPU);
        FPU.show();
        }
    }//GEN-LAST:event_menu_pinjam_jm_ukmActionPerformed

    private void menu_pinjam_jm_kprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pinjam_jm_kprActionPerformed
        // TODO add your handling code here:
           if (!FPK.isVisible()) {
        jDesktopPane1.add(FPK);
        FPK.show();
        }
    }//GEN-LAST:event_menu_pinjam_jm_kprActionPerformed

    private void menu_pinjam_kr_bgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pinjam_kr_bgActionPerformed
        // TODO add your handling code here:
           if (!FPG.isVisible()) {
        jDesktopPane1.add(FPG);
        FPG.show();
        }
    }//GEN-LAST:event_menu_pinjam_kr_bgActionPerformed

    private void menu_pinjam_kr_ukmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pinjam_kr_ukmActionPerformed
        // TODO add your handling code here:
           if (!FPR.isVisible()) {
        jDesktopPane1.add(FPR);
        FPR.show();
        }
    }//GEN-LAST:event_menu_pinjam_kr_ukmActionPerformed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(rootPane,"yakin ingin Logout ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        dispose();
        login l = new login();
        l.setVisible(true);
        } 
    }//GEN-LAST:event_logoutMousePressed

    private void keluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMousePressed
        // TODO add your handling code here:
        int conf = JOptionPane.showConfirmDialog(rootPane,"Apakah anda yakin ingin keluar dari Aplikasi ini ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        System.exit(0);
        }
    }//GEN-LAST:event_keluarMousePressed

    private void menu_kr_bgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_kr_bgActionPerformed
        // TODO add your handling code here:
        if (!FKB.isVisible()) {
        jDesktopPane1.add(FKB);
        FKB.show();
       }
    }//GEN-LAST:event_menu_kr_bgActionPerformed

    private void menu_kr_ukmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_kr_ukmActionPerformed
        // TODO add your handling code here:
         if (!FKU.isVisible()) {
        jDesktopPane1.add(FKU);
        FKU.show();
       }
    }//GEN-LAST:event_menu_kr_ukmActionPerformed

    private void logout_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_MousePressed
        // TODO add your handling code here:
         int conf = JOptionPane.showConfirmDialog(rootPane,"yakin ingin Logout ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        dispose();
        login l = new login();
        l.setVisible(true);
        } 
    }//GEN-LAST:event_logout_MousePressed

    private void exit_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_MousePressed
        // TODO add your handling code here:
         int conf = JOptionPane.showConfirmDialog(rootPane,"Apakah anda yakin ingin keluar dari Aplikasi ini ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
        System.exit(0);
        }
    }//GEN-LAST:event_exit_MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }
    
    private void jam() {
     Timer tt = new Timer();
     tt.scheduleAtFixedRate(new TimerTask() {
         
         @Override
         public void run() {
             lbljam.setText(new SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
             
         }
     }, 0, 1000);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buat_user;
    private javax.swing.JLabel exit_;
    public javax.swing.JLabel infonama;
    public javax.swing.JLabel infouser;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JLabel lbljam;
    private javax.swing.JLabel lbltgl;
    private javax.swing.JMenuItem logout;
    private javax.swing.JLabel logout_;
    private javax.swing.JMenuItem menu_jm_kpr;
    private javax.swing.JMenuItem menu_jm_personal;
    private javax.swing.JMenuItem menu_jm_ukm;
    private javax.swing.JMenuItem menu_kr_bg;
    private javax.swing.JMenuItem menu_kr_ukm;
    private javax.swing.JMenuItem menu_pengembalian;
    private javax.swing.JMenuItem menu_pinjam_jm_kpr;
    private javax.swing.JMenuItem menu_pinjam_jm_ukm;
    private javax.swing.JMenuItem menu_pinjam_kr_bg;
    private javax.swing.JMenuItem menu_pinjam_kr_ukm;
    private javax.swing.JMenuItem menu_pinjam_personal;
    // End of variables declaration//GEN-END:variables
}
